version: '3.8'

services:
  db:
    image: docker.io/library/postgres:alpine
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: portfolio
    ports:
      - '5432:5432'
